// INDEPENDENT AUDIT — drives the real app over CDP and checks EVERY piece
// of this branch's engineering, plus two adversarial risks the existing
// tests do NOT cover:
//   RISK A: BM25 is lexical + unstemmed. A behavioral question whose
//           answering evidence uses DIFFERENT vocabulary may not be
//           retrieved → ungrounded or fabricated answer on a large KB.
//   RISK B: the cover is generated by a model that never sees the resume,
//           yet is told to COMMIT to a direction, and the main model is
//           then told to stay consistent with it → fabrication lock-in.
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const WebSocket = require('ws');
const jwt = require('jsonwebtoken');
const Database = require('better-sqlite3');
const path = require('node:path');

const R = [];
const rec = (name, ok, detail) => { R.push({ name, ok }); console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? '  — ' + detail : ''}`); };
const note = (s) => console.log(`      ${s}`);
const sleep = ms => new Promise(r => setTimeout(r, ms));

const list = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const t = list.find(x => x.type === 'page' && x.url.includes('localhost:3005') && !x.url.includes('popout'));
if (!t) { console.log('no app window'); process.exit(1); }
const ws = new WebSocket(t.webSocketDebuggerUrl, { maxPayload: 128 * 1024 * 1024 });
await new Promise(r => ws.on('open', r));
let id = 0; const P = new Map(); const consoleErrs = [];
ws.on('message', raw => {
  const m = JSON.parse(raw);
  if (m.id && P.has(m.id)) { P.get(m.id)(m); P.delete(m.id); }
  if (m.method === 'Runtime.consoleAPICalled' && m.params?.type === 'error') consoleErrs.push((m.params.args || []).map(a => a.value ?? a.description ?? '').join(' ').slice(0, 200));
  if (m.method === 'Runtime.exceptionThrown') consoleErrs.push('EXC: ' + (m.params?.exceptionDetails?.exception?.description || '').slice(0, 200));
});
const cmd = (method, params = {}) => new Promise(res => { const i = ++id; P.set(i, res); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = (e, ap = false) => cmd('Runtime.evaluate', { expression: e, awaitPromise: ap, returnByValue: true }).then(r => r.result?.result?.value);
const waitFor = async (x, ms = 40000, every = 40) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { try { if (await ev(x)) return true; } catch {} await sleep(every); } return false; };
await cmd('Runtime.enable'); await cmd('Page.enable');

const DOM = `(function(){var b=Array.prototype.slice.call(document.querySelectorAll('.flex.justify-end,.flex.justify-start'));var sl=0,ai=0,last='',users=0;for(var i=0;i<b.length;i++){var x=b[i],md=x.querySelector('.markdown-body'),tx=md?md.innerText.trim():'';if(x.querySelector('.stream-caret')){sl=tx.length;}else if(x.classList.contains('justify-end')){if(tx)users++;}else if(tx){ai++;last=tx;}}return{streamingLen:sl,aiCommitted:ai,userCount:users,lastAi:last,thinking:/THINKING \\(/.test(document.body.innerText)};})()`;
const st = () => ev(`JSON.stringify(${DOM})`).then(JSON.parse);

// ── auth ──
const dbPath = process.env.DATABASE_PATH || path.join(process.cwd(), 'data', 'minicaai.db');
const ddb = new Database(dbPath, { readonly: true });
const email = (process.env.ADMIN_EMAILS || '').split(',')[0].trim();
const u = ddb.prepare('SELECT id,email,name FROM users WHERE email = ?').get(email);
const lic = ddb.prepare('SELECT tier,status,expires_at,sessions_limit,sessions_used,credits_remaining_seconds,credits_expire_at,trial_remaining_seconds FROM licenses WHERE user_id = ?').get(u.id);
const token = jwt.sign({ id: u.id, email: u.email }, process.env.JWT_SECRET, { expiresIn: '2h' });
await ev(`(()=>{localStorage.setItem('minicaai_token',${JSON.stringify(token)});localStorage.setItem('minicaai_auth',${JSON.stringify(JSON.stringify({ id: u.id, email: u.email, name: u.name || 'A' }))});localStorage.setItem('minicaai_license',${JSON.stringify(JSON.stringify(lic))});localStorage.setItem('SELECTED_MODEL','openai');localStorage.setItem('REASONING_EFFORT','none');localStorage.setItem('GENERAL_MODE','false');return 1;})()`);
await cmd('Page.reload', { ignoreCache: true });
await sleep(3000);
const up = await waitFor(`typeof window.__dev_executeSend==='function'`, 25000, 300);
rec('app boots + dev hooks present', up);
if (!up) { ws.close(); process.exit(1); }

const ask = async (q, { fresh = true } = {}) => {
  if (fresh) { await ev(`window.__dev_newSession()`); await sleep(1000); }
  await waitFor(`window.__dev_isProcessing ? !window.__dev_isProcessing() : true`, 40000, 200);
  const base = await st();
  const t0 = Date.now();
  await ev(`(window.__dev_executeSend(${JSON.stringify(q)}),1)`);
  await waitFor(`(function(){var s=${DOM};return s.streamingLen>0||s.aiCommitted>${base.aiCommitted};})()`, 40000, 30);
  const paint = Date.now() - t0;
  await waitFor(`(function(){var s=${DOM};return !s.thinking && s.aiCommitted>${base.aiCommitted};})()`, 90000, 400);
  await sleep(300);
  const s = await st();
  return { paint, answer: s.lastAi, state: s };
};

const bigKb = (extra) => `(function(){
  var files=[];
  files.push({id:'resume',name:'resume.md',type:'resume',content:${JSON.stringify(extra)}});
  files.push({id:'jd',name:'jd.md',type:'jd',content:'Senior Data Engineer, payments platform. Streaming, exactly-once, CDC, lakehouse, Kubernetes, cost control.'});
  var block=('Design note: ingestion partitioning retries dedupe keys backfill strategy SLO budgets for the service. The team reviewed throughput and storage layout. ').repeat(28);
  for(var i=1;i<=98;i++) files.push({id:'f'+i,name:'note_'+i+'.md',type:'custom',content:'## Note '+i+'\\n'+block});
  window.__dev_setContextFiles(files);
  return files.length;
})()`;

// The resume deliberately uses DIFFERENT vocabulary than the behavioral
// question that needs it ("disagreed/pushed back/bake-off" vs the question's
// "conflict/disagreement"), and names a tech the candidate did NOT use.
const RESUME = `Alex Morgan — Senior Data Engineer.

At Meridian Health I ran a two-week bake-off when the group could not agree on the ingestion backbone. I pushed hard for Kinesis; the others wanted Kafka. I was overruled, we shipped Kafka, and I later admitted the throughput numbers proved them right. That episode changed how I argue technical positions.

I migrated a 41-billion-row PostgreSQL fleet onto Aurora, cutting checkout p99 from 820ms to 90ms.

I have never worked with Snowflake or dbt.`;

console.log('\n════ 1. NO-FILES BASELINE (depth routing + cover) ════');
await ev(`window.__dev_setContextFiles([])`); await sleep(400);
const shallow = await ask('What is the difference between a process and a thread?');
rec('shallow concept answers', shallow.answer.length > 80, `paint=${shallow.paint}ms`);
const deep = await ask('How would you design a distributed rate limiter with per-user quotas across regions?');
rec('deep design answers', deep.answer.length > 150, `paint=${deep.paint}ms`);
note('deep: ' + deep.answer.slice(0, 150).replace(/\s+/g, ' '));

console.log('\n════ 2. LARGE KB — cost + lexical grounding ════');
await ev(`window.__dev_newSession()`); await sleep(900);
await ev(bigKb(RESUME)); await sleep(700);
const info = JSON.parse(await ev('JSON.stringify(window.__dev_contextInfo())'));
note(`KB: ${info.count} files, ${info.totalChars.toLocaleString()} chars`);
const lexical = await ask('Tell me about the database migration you led.', { fresh: false });
const lexOk = /meridian|41[\s-]?billion|aurora|820/i.test(lexical.answer);
rec('RISK-free lexical retrieval grounded', lexOk, `paint=${lexical.paint}ms`);
note('answer: ' + lexical.answer.slice(0, 160).replace(/\s+/g, ' '));

console.log('\n════ 3. RISK A — behavioral Q, vocabulary MISMATCH ════');
note('Q uses "conflict/disagreement"; resume says "could not agree / pushed hard / overruled"');
const behav = await ask('Tell me about a time you had a conflict with your team.', { fresh: false });
const behavGrounded = /bake-?off|kinesis|kafka|overrul|meridian|argue|admitted/i.test(behav.answer);
rec('RISK A: behavioral answer grounded in real resume episode', behavGrounded);
note('answer: ' + behav.answer.slice(0, 260).replace(/\s+/g, ' '));

console.log('\n════ 4. RISK B — cover fabrication on un-had experience ════');
note('Resume explicitly says: "I have never worked with Snowflake or dbt."');
const fab = await ask('Can you walk me through how you have used Snowflake and dbt in production?', { fresh: false });
const admits = /never|haven[’']?t|have not|not something i|no direct|didn[’']?t|no hands.?on|not used/i.test(fab.answer);
// An audible retraction means the cover fabricated and the main model had
// to walk it back OUT LOUD — the exact credibility hit we're preventing.
const retracts = /actually,? i (need to |should )?correct|correct that opening|let me correct|i misspoke|scratch that|to be accurate,? i/i.test(fab.answer);
rec('RISK B: admits gap AND no audible retraction', admits && !retracts, `admits=${admits} retracted=${retracts}`);
note('answer: ' + fab.answer.slice(0, 260).replace(/\s+/g, ' '));

console.log('\n════ 5. INTERRUPTION + BACKCHANNEL + SESSION ════');
await waitFor(`window.__dev_isProcessing ? !window.__dev_isProcessing() : true`, 40000, 200);
const b4 = await st();
await ev(`(window.__dev_executeSend("How would you design a scalable notification system for millions of users?"),1)`);
const streaming = await waitFor(`(${DOM}).streamingLen>60`, 30000, 25);
const mid = await st();
const partial = mid.streamingText || mid.lastAi;
await ev(`(window.__dev_executeSend("Actually, how do you stop duplicate notifications?"),1)`);
const settled = await waitFor(`(function(){var s=${DOM};return !s.thinking && s.userCount>=${b4.userCount + 2} && s.aiCommitted>=${b4.aiCommitted + 2};})()`, 90000, 400);
const after = await st();
rec('interruption: both questions answered', settled && after.aiCommitted >= b4.aiCommitted + 2, `caughtMidStream=${streaming} aiDelta=${after.aiCommitted - b4.aiCommitted}`);
note('follow-up: ' + after.lastAi.slice(0, 180).replace(/\s+/g, ' '));

const bc = JSON.parse(await ev(`import('/services/interruption.ts').then(m=>JSON.stringify({a:m.isBackchannelOnly('okay'),b:m.isBackchannelOnly('mm-hmm'),c:m.isBackchannelOnly('okay so how would you scale it'),d:m.isBackchannelOnly('why?')})).catch(e=>JSON.stringify({err:String(e).slice(0,80)}))`, true));
rec('backchannel gate correct', bc.a === true && bc.b === true && bc.c === false && bc.d === false, JSON.stringify(bc));

await ev(`window.__dev_newSession()`); await sleep(1200);
const cleared = JSON.parse(await ev('JSON.stringify(window.__dev_contextInfo())'));
rec('new session clears files', cleared.count === 0 && cleared.totalChars === 0, JSON.stringify(cleared));

const realErrs = consoleErrs.filter(e => !/ERR_CONNECTION_REFUSED.*9222|Autofill|DevTools|favicon|Download the React|electron-log/i.test(e));
rec('zero runtime console errors', realErrs.length === 0, `${realErrs.length}`);
if (realErrs.length) realErrs.slice(0, 4).forEach(e => note(e));

console.log(`\n════ ${R.filter(r => r.ok).length}/${R.length} PASSED ════`);
ws.close(); process.exit(0);
